server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_db
    username: postgres
    password: your_super_secret_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # This tells Hibernate to automatically create your database tables based on your Java code!
    show-sql: true # Prints the SQL Hibernate generates to your terminal so you can see the magic
    properties:
      hibernate:
        format_sql: true

# Resilience4j MUST be at the root level (all the way to the left), not inside 'spring'
resilience4j.circuitbreaker:
  instances:
    vectorMathService:               # Must match the 'name' attribute in @CircuitBreaker annotation!
      slidingWindowSize: 10          # Check the last 10 requests
      failureRateThreshold: 50       # If 50% (3+ out of 5) of them fail, TRIP THE BREAKER!
      waitDurationInOpenState: 5000ms # Stay open (blocking traffic) for 5 seconds before trying again.
      permittedNumberOfCallsInHalfOpenState: 2 # Let 2 test requests in to see if the server recovered